export interface GroupInfo {
  name: string;
  description: string;
  slugs: string[];
}

export const GROUP_TAXONOMY: GroupInfo[] = [
  {
    name: "Wallet & Identity",
    description: "Account surfaces, connect flows, and \"who am I on-chain.\"",
    slugs: [
      "accountcard",
      "authcard",
      "addressdisplay",
      "balancedisplay",
      "cryptouserprofile",
      "cryptowalletdashboard",
      "cryptowalletdrawer",
      "cryptowalletmain",
      "cryptowalletmenusheet",
      "cryptowalletsettings",
      "identitycard",
      "multiwalletswitcher",
      "solanaidentitycard",
      "solanawalletcard",
      "walletmodal",
      "walletsheet",
    ],
  },
  {
    name: "Tokens & Assets",
    description: "Anything that represents, picks, or describes a token.",
    slugs: [
      "cryptotokendetailsscreen",
      "solanatokencard",
      "tokencombobox",
      "tokencommand",
      "tokenicon",
      "tokenicongroup",
      "tokeninput",
      "tokenlistitem",
      "tokenmarketcapbadge",
      "tokenpair",
      "tokensafetyscore",
    ],
  },
  {
    name: "Swap, Trade & Orders",
    description: "Execution UI: swap boxes, books, sliders, fees.",
    slugs: [
      "cryptoswapbox",
      "cryptotradingterminal",
      "limitordercard",
      "leverageslider",
      "orderbook",
      "orderform",
      "priorityfeeselector",
      "routesummary",
      "slippageselector",
      "solanaswapcard",
      "swapwidget",
      "tradebox",
      "tradebuttons",
      "tradetogglepill",
    ],
  },
  {
    name: "DeFi Positions & Yield",
    description: "Lending, staking, pools, farms, treasury.",
    slugs: [
      "borrowlendposition",
      "delegationcard",
      "liquiditypoolcard",
      "poolcard",
      "pooltable",
      "positioncard",
      "positiontable",
      "stakingcard",
      "treasuryoverview",
      "yieldfarmrow",
    ],
  },
  {
    name: "NFTs",
    description: "Gallery, listing, traits, offers, floor.",
    slugs: [
      "floorpricetracker",
      "nftgallerygrid",
      "nftlistingmodal",
      "nftmakeoffercard",
      "nftraritybadge",
      "nfttraitpill",
      "solananftcard",
    ],
  },
  {
    name: "Charts & Metrics",
    description: "Price, TVL, sales, gauges, progress.",
    slugs: [
      "cryptoprogressring",
      "cryptoprojectprogress",
      "cryptosalescandlestickchart",
      "cryptosaleschart",
      "cryptosalessegmentedbars",
      "cryptosalesverticalgraph",
      "cryptotvlanalyticschart",
      "cryptotvlsparkbarwidget",
      "financialmetricsgrid",
      "gauge",
      "heatmapchart",
      "pricechart",
      "priceticker",
      "progressring",
      "segmentedprogresscard",
      "statcard",
    ],
  },
  {
    name: "Predictions & Markets",
    description: "Up/down, odds, candidates, carousels.",
    slugs: [
      "cryptopredictioncandidatecard",
      "cryptopredictionoddsrow",
      "cryptopredictionquickgrid",
      "cryptopredictionsearchbar",
      "cryptopredictiontabselector",
      "cryptoupdowntargetline",
      "cryptoupdownupcomingcarousel",
    ],
  },
  {
    name: "Transactions & Activity",
    description: "Status, receipts, tables, toasts, history.",
    slugs: [
      "activityfeed",
      "batchtransactionlist",
      "instructiondecoder",
      "signaturestatusbadge",
      "solanatransactionstatus",
      "transactionmodal",
      "transactionreceipt",
      "txntable",
      "txntoast",
    ],
  },
  {
    name: "Buttons, Actions & Menus",
    description: "Click / hold / confirm / speed-dial patterns.",
    slugs: [
      "actionbox",
      "buttongooey",
      "clicktocopy",
      "cooldownbutton",
      "copybutton",
      "cryptospeeddialactionmenu",
      "evilbuttonsgroup",
      "floatingactionbutton",
      "gooeymenu",
      "holdtoconfirm",
      "solanapaybutton",
      "speeddial",
      "uxbutton",
      "multiplestatebutton",
    ],
  },
  {
    name: "Inputs, Forms & Selectors",
    description: "Fields, sliders, toggles, OTP, command.",
    slugs: [
      "commandpalette",
      "drawcheckbox",
      "inputborderspotlight",
      "inputmorphmessage",
      "liquidradio",
      "morphingfeedbackpopover",
      "otpinput",
      "passwordinput",
      "popoverslideselector",
      "slider",
      "spotlightinput",
      "togglegroup",
      "togglepill",
    ],
  },
  {
    name: "Feedback, Status & Notifications",
    description: "Badges, alerts, toasts, success/error motion.",
    slugs: [
      "blueconfettitransaction",
      "cryptocookiebanner",
      "dynamicislandstatus",
      "errorstateshake",
      "multistatebadge",
      "neonstatusbadge",
      "networkbadge",
      "notificationbadge",
      "notificationsstack",
      "securityalertbanner",
      "snsdomainbadge",
      "sonner",
      "statusbadgepill",
      "successcheck",
      "trendbadge",
    ],
  },
  {
    name: "Navigation, Layout & Overlays",
    description: "Tabs, drawers, sheets, stacks, carousels.",
    slugs: [
      "animatedpills",
      "animatedtabs",
      "cardstack",
      "categorytagpills",
      "cryptoexplorecategories",
      "cryptoexplorehub",
      "cryptoexplorenews",
      "eventtagpills",
      "familydialog",
      "familydrawer",
      "familypopovermenu",
      "logocarousel",
      "marquee",
      "smoothtabs",
      "underlayactionsheet",
    ],
  },
  {
    name: "Network, Security & Infra",
    description: "RPC, gas, keys, health, pay.",
    slugs: [
      "gasmeter",
      "keypairgenerator",
      "qrcode",
      "rpcnodemonitor",
      "secretkeywarningbox",
      "solananetworkhealth",
    ],
  },
  {
    name: "Engagement & Gamification",
    description: "Quests, streaks, leaderboards, airdrops, voting.",
    slugs: [
      "airdropclaimwidget",
      "cryptosubscriptioncard",
      "cryptotraderleaderboard",
      "leaderboardrow",
      "proposalcard",
      "questcard",
      "runstatsstacks",
      "spincounter",
      "spinningcounter",
      "steptrackerwidget",
      "streakcounter",
      "timeline",
      "votinginterface",
    ],
  },
  {
    name: "Checkout & Commerce",
    description: "Pay / subscribe / checkout surfaces.",
    slugs: [
      "cryptocheckoutcard",
    ],
  },
  {
    name: "Visual / Motion primitives",
    description: "Look-and-feel helpers that wrap other components.",
    slugs: [
      "glassfilter",
      "healthbar",
      "skeleton",
      "skeletonreveal",
    ],
  },
];

const SLUG_TO_GROUP = new Map<string, string>();

for (const group of GROUP_TAXONOMY) {
  for (const slug of group.slugs) {
    SLUG_TO_GROUP.set(slug.toLowerCase(), group.name);
  }
}

export function getGroupForSlug(slug: string): string {
  return SLUG_TO_GROUP.get(slug.toLowerCase()) || "Other";
}
