/* eslint-disable @typescript-eslint/no-explicit-any */
export interface RegistryItem {
  preview?: string;
  image?: string;
  dependencies?: any[];
  props?: any[];
  credits?: any[];
  id: string;
  slug: string;
  title: string;
  name: string;
  group: string;
  category: string;
  registry: string;
  file: string;
  thumb?: string;
  description: string;
  source: string;
  interaction: string;
  usage: string;
  href: string;
}

export const REGISTRY_REPO = "Subhan-code/oxygen_ui";
export const REGISTRY_HOMEPAGE = "https://github.com/Subhan-code/oxygen_ui";

export function validateRegistry(items: RegistryItem[]): void {
  const titles = new Set<string>();
  const slugs = new Set<string>();
  const ids = new Set<string>();

  for (const item of items) {
    const normTitle = item.title.trim().toLowerCase();
    if (titles.has(normTitle)) {
      throw new Error(`Duplicate registry title: "${item.title}" (${item.slug})`);
    }
    if (slugs.has(item.slug)) {
      throw new Error(`Duplicate registry slug: "${item.slug}"`);
    }
    if (ids.has(item.id)) {
      throw new Error(`Duplicate registry id: "${item.id}" (${item.title})`);
    }
    titles.add(normTitle);
    slugs.add(item.slug);
    ids.add(item.id);
  }
}

export function getAllSlugs(): string[] {
  return REGISTRY.map((item) => item.slug);
}

export function getComponentBySlug(slug: string): RegistryItem | undefined {
  return REGISTRY.find((item) => item.slug === slug);
}

export const REGISTRY: RegistryItem[] = [
  {
    id: "1",
    slug: "accountcard",
    title: "Account Card",
    group: "Solana & Web3 Primitives",
    name: "Account Card",
    category: "Solana & Web3 Primitives",
    registry: "Solana & Web3 Primitives",
    file: "components/ui/account-card.tsx",
    description: "High performance Apple-styled Account Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/account-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { AccountCard } from "@/components/ui/account-card.tsx"`,
    href: "/components/accountcard"
  },
  {
    id: "2",
    slug: "actionbox",
    title: "Action Box",
    group: "Buttons, Actions & Menus",
    name: "Action Box",
    category: "Buttons, Actions & Menus",
    registry: "Buttons, Actions & Menus",
    file: "components/ui/action-box.tsx",
    description: "High performance Apple-styled Action Box component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/action-box.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { ActionBox } from "@/components/ui/action-box.tsx"`,
    href: "/components/actionbox"
  },
  {
    id: "3",
    slug: "activityfeed",
    title: "Activity Feed",
    group: "Transactions & Activity",
    name: "Activity Feed",
    category: "Transactions & Activity",
    registry: "Transactions & Activity",
    file: "components/ui/activity-feed.tsx",
    description: "High performance Apple-styled Activity Feed component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/activity-feed.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { ActivityFeed } from "@/components/ui/activity-feed.tsx"`,
    href: "/components/activityfeed"
  },
  {
    id: "4",
    slug: "addressdisplay",
    title: "Address Display",
    group: "Wallet & Identity",
    name: "Address Display",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/address-display.tsx",
    description: "High performance Apple-styled Address Display component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/address-display.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { AddressDisplay } from "@/components/ui/address-display.tsx"`,
    href: "/components/addressdisplay"
  },

  {
    id: "6",
    slug: "animatedtabs",
    title: "Animated Tabs",
    group: "Navigation, Layout & Overlays",
    name: "Animated Tabs",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/animated-tabs.tsx",
    description: "High performance Apple-styled Animated Tabs component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/animated-tabs.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { AnimatedTabs } from "@/components/ui/animated-tabs.tsx"`,
    href: "/components/animatedtabs"
  },
  {
    id: "7",
    slug: "authcard",
    title: "Auth Card",
    group: "Wallet & Identity",
    name: "Auth Card",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/auth-card.tsx",
    description: "High performance Apple-styled Auth Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/auth-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { AuthCard } from "@/components/ui/auth-card.tsx"`,
    href: "/components/authcard"
  },
  {
    id: "8",
    slug: "balancedisplay",
    title: "Balance Display",
    group: "Wallet & Identity",
    name: "Balance Display",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/balance-display.tsx",
    description: "High performance Apple-styled Balance Display component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/balance-display.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { BalanceDisplay } from "@/components/ui/balance-display.tsx"`,
    href: "/components/balancedisplay"
  },

  {
    id: "13",
    slug: "cardstack",
    title: "Card Stack",
    group: "Navigation, Layout & Overlays",
    name: "Card Stack",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/card-stack.tsx",
    description: "High performance Apple-styled Card Stack component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/card-stack.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CardStack } from "@/components/ui/card-stack.tsx"`,
    href: "/components/cardstack"
  },


  {
    id: "19",
    slug: "cryptocheckoutcard",
    title: "Crypto Checkout Card",
    group: "Checkout & Commerce",
    name: "Crypto Checkout Card",
    category: "Checkout & Commerce",
    registry: "Checkout & Commerce",
    file: "components/ui/crypto-checkout-card.tsx",
    description: "High performance Apple-styled Crypto Checkout Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-checkout-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoCheckoutCard } from "@/components/ui/crypto-checkout-card.tsx"`,
    href: "/components/cryptocheckoutcard"
  },
  {
    id: "21",
    slug: "cryptoexplorecategories",
    title: "Crypto Explore Categories",
    group: "Navigation, Layout & Overlays",
    name: "Crypto Explore Categories",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/crypto-explore-categories.tsx",
    description: "High performance Apple-styled Crypto Explore Categories component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-explore-categories.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoExploreCategories } from "@/components/ui/crypto-explore-categories.tsx"`,
    href: "/components/cryptoexplorecategories"
  },
  {
    id: "24",
    slug: "cryptopredictioncandidatecard",
    title: "Crypto Prediction Candidate Card",
    group: "Predictions & Markets",
    name: "Crypto Prediction Candidate Card",
    category: "Predictions & Markets",
    registry: "Predictions & Markets",
    file: "components/ui/crypto-prediction-candidate-card.tsx",
    description: "High performance Apple-styled Crypto Prediction Candidate Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-prediction-candidate-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoPredictionCandidateCard } from "@/components/ui/crypto-prediction-candidate-card.tsx"`,
    href: "/components/cryptopredictioncandidatecard"
  },

  {
    id: "31",
    slug: "cryptosalescandlestickchart",
    title: "Crypto Sales Candlestick Chart",
    group: "Charts & Metrics",
    name: "Crypto Sales Candlestick Chart",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/crypto-sales-candlestick-chart.tsx",
    description: "High performance Apple-styled Crypto Sales Candlestick Chart component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-sales-candlestick-chart.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoSalesCandlestickChart } from "@/components/ui/crypto-sales-candlestick-chart.tsx"`,
    href: "/components/cryptosalescandlestickchart"
  },
  {
    id: "33",
    slug: "cryptosalessegmentedbars",
    title: "Crypto Sales Segmented Bars",
    group: "Charts & Metrics",
    name: "Crypto Sales Segmented Bars",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/crypto-sales-segmented-bars.tsx",
    description: "High performance Apple-styled Crypto Sales Segmented Bars component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-sales-segmented-bars.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoSalesSegmentedBars } from "@/components/ui/crypto-sales-segmented-bars.tsx"`,
    href: "/components/cryptosalessegmentedbars"
  },
  {
    id: "34",
    slug: "cryptosalesverticalgraph",
    title: "Crypto Sales Vertical Graph",
    group: "Charts & Metrics",
    name: "Crypto Sales Vertical Graph",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/crypto-sales-vertical-graph.tsx",
    description: "High performance Apple-styled Crypto Sales Vertical Graph component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-sales-vertical-graph.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoSalesVerticalGraph } from "@/components/ui/crypto-sales-vertical-graph.tsx"`,
    href: "/components/cryptosalesverticalgraph"
  },

  {
    id: "36",
    slug: "cryptosubscriptioncard",
    title: "Crypto Subscription Card",
    group: "Engagement & Gamification",
    name: "Crypto Subscription Card",
    category: "Engagement & Gamification",
    registry: "Engagement & Gamification",
    file: "components/ui/crypto-subscription-card.tsx",
    description: "High performance Apple-styled Crypto Subscription Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-subscription-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoSubscriptionCard } from "@/components/ui/crypto-subscription-card.tsx"`,
    href: "/components/cryptosubscriptioncard"
  },
  {
    id: "37",
    slug: "cryptoswapbox",
    title: "Crypto Swap Box",
    group: "Swap, Trade & Orders",
    name: "Crypto Swap Box",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/crypto-swap-box.tsx",
    description: "High performance Apple-styled Crypto Swap Box component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-swap-box.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoSwapBox } from "@/components/ui/crypto-swap-box.tsx"`,
    href: "/components/cryptoswapbox"
  },


  {
    id: "48",
    slug: "cryptouserprofile",
    title: "Crypto User Profile",
    group: "Wallet & Identity",
    name: "Crypto User Profile",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/crypto-user-profile.tsx",
    description: "High performance Apple-styled Crypto User Profile component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-user-profile.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoUserProfile } from "@/components/ui/crypto-user-profile.tsx"`,
    href: "/components/cryptouserprofile"
  },
  {
    id: "49",
    slug: "cryptowalletdashboard",
    title: "Crypto Wallet Dashboard",
    group: "Wallet & Identity",
    name: "Crypto Wallet Dashboard",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/crypto-wallet-dashboard.tsx",
    description: "High performance Apple-styled Crypto Wallet Dashboard component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-wallet-dashboard.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoWalletDashboard } from "@/components/ui/crypto-wallet-dashboard.tsx"`,
    href: "/components/cryptowalletdashboard"
  },
  {
    id: "50",
    slug: "cryptowalletdrawer",
    title: "Crypto Wallet Drawer",
    group: "Wallet & Identity",
    name: "Crypto Wallet Drawer",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/crypto-wallet-drawer.tsx",
    description: "High performance Apple-styled Crypto Wallet Drawer component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-wallet-drawer.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoWalletDrawer } from "@/components/ui/crypto-wallet-drawer.tsx"`,
    href: "/components/cryptowalletdrawer"
  },
  {
    id: "51",
    slug: "cryptowalletmain",
    title: "Crypto Wallet Main",
    group: "Wallet & Identity",
    name: "Crypto Wallet Main",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/crypto-wallet-main.tsx",
    description: "High performance Apple-styled Crypto Wallet Main component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-wallet-main.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoWalletMain } from "@/components/ui/crypto-wallet-main.tsx"`,
    href: "/components/cryptowalletmain"
  },
  {
    id: "52",
    slug: "cryptowalletmenusheet",
    title: "Crypto Wallet Menu Sheet",
    group: "Wallet & Identity",
    name: "Crypto Wallet Menu Sheet",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/crypto-wallet-menu-sheet.tsx",
    description: "High performance Apple-styled Crypto Wallet Menu Sheet component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-wallet-menu-sheet.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoWalletMenuSheet } from "@/components/ui/crypto-wallet-menu-sheet.tsx"`,
    href: "/components/cryptowalletmenusheet"
  },
  {
    id: "53",
    slug: "cryptowalletsettings",
    title: "Crypto Wallet Settings",
    group: "Wallet & Identity",
    name: "Crypto Wallet Settings",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/crypto-wallet-settings.tsx",
    description: "High performance Apple-styled Crypto Wallet Settings component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/crypto-wallet-settings.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { CryptoWalletSettings } from "@/components/ui/crypto-wallet-settings.tsx"`,
    href: "/components/cryptowalletsettings"
  },

  {
    id: "55",
    slug: "errorstateshake",
    title: "Error State Shake",
    group: "Feedback, Status & Notifications",
    name: "Error State Shake",
    category: "Feedback, Status & Notifications",
    registry: "Feedback, Status & Notifications",
    file: "components/ui/error-state-shake.tsx",
    description: "High performance Apple-styled Error State Shake component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/error-state-shake.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { ErrorStateShake } from "@/components/ui/error-state-shake.tsx"`,
    href: "/components/errorstateshake"
  },

  {
    id: "58",
    slug: "familydialog",
    title: "Family Dialog",
    group: "Navigation, Layout & Overlays",
    name: "Family Dialog",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/family-dialog.tsx",
    description: "High performance Apple-styled Family Dialog component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/family-dialog.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { FamilyDialog } from "@/components/ui/family-dialog.tsx"`,
    href: "/components/familydialog"
  },
  {
    id: "59",
    slug: "familydrawer",
    title: "Family Drawer",
    group: "Navigation, Layout & Overlays",
    name: "Family Drawer",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/family-drawer.tsx",
    description: "High performance Apple-styled Family Drawer component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/family-drawer.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { FamilyDrawer } from "@/components/ui/family-drawer.tsx"`,
    href: "/components/familydrawer"
  },
  {
    id: "60",
    slug: "familypopovermenu",
    title: "Family Popover Menu",
    group: "Navigation, Layout & Overlays",
    name: "Family Popover Menu",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/family-popover-menu.tsx",
    description: "High performance Apple-styled Family Popover Menu component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/family-popover-menu.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { FamilyPopoverMenu } from "@/components/ui/family-popover-menu.tsx"`,
    href: "/components/familypopovermenu"
  },
  {
    id: "61",
    slug: "financialmetricsgrid",
    title: "Financial Metrics Grid",
    group: "Charts & Metrics",
    name: "Financial Metrics Grid",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/financial-metrics-grid.tsx",
    description: "High performance Apple-styled Financial Metrics Grid component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/financial-metrics-grid.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { FinancialMetricsGrid } from "@/components/ui/financial-metrics-grid.tsx"`,
    href: "/components/financialmetricsgrid"
  },

  {
    id: "65",
    slug: "gauge",
    title: "Gauge",
    group: "Charts & Metrics",
    name: "Gauge",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/gauge.tsx",
    description: "High performance Apple-styled Gauge component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/gauge.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { Gauge } from "@/components/ui/gauge.tsx"`,
    href: "/components/gauge"
  },
  {
    id: "67",
    slug: "gooeymenu",
    title: "Gooey Menu",
    group: "Buttons, Actions & Menus",
    name: "Gooey Menu",
    category: "Buttons, Actions & Menus",
    registry: "Buttons, Actions & Menus",
    file: "components/ui/gooey-menu.tsx",
    description: "High performance Apple-styled Gooey Menu component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/gooey-menu.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { GooeyMenu } from "@/components/ui/gooey-menu.tsx"`,
    href: "/components/gooeymenu"
  },

  {
    id: "72",
    slug: "inputmorphmessage",
    title: "Input Morph Message",
    group: "Inputs, Forms & Selectors",
    name: "Input Morph Message",
    category: "Inputs, Forms & Selectors",
    registry: "Inputs, Forms & Selectors",
    file: "components/ui/input-morph-message.tsx",
    description: "High performance Apple-styled Input Morph Message component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/input-morph-message.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { InputMorphMessage } from "@/components/ui/input-morph-message.tsx"`,
    href: "/components/inputmorphmessage"
  },


  {
    id: "76",
    slug: "leverageslider",
    title: "Leverage Slider",
    group: "Swap, Trade & Orders",
    name: "Leverage Slider",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/leverage-slider.tsx",
    description: "High performance Apple-styled Leverage Slider component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/leverage-slider.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { LeverageSlider } from "@/components/ui/leverage-slider.tsx"`,
    href: "/components/leverageslider"
  },
  {
    id: "78",
    slug: "liquidradio",
    title: "Liquid Radio",
    group: "Inputs, Forms & Selectors",
    name: "Liquid Radio",
    category: "Inputs, Forms & Selectors",
    registry: "Inputs, Forms & Selectors",
    file: "components/ui/liquid-radio.tsx",
    description: "High performance Apple-styled Liquid Radio component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/liquid-radio.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { LiquidRadio } from "@/components/ui/liquid-radio.tsx"`,
    href: "/components/liquidradio"
  },
  {
    id: "79",
    slug: "liquiditypoolcard",
    title: "Liquidity Pool Card",
    group: "DeFi Positions & Yield",
    name: "Liquidity Pool Card",
    category: "DeFi Positions & Yield",
    registry: "DeFi Positions & Yield",
    file: "components/ui/liquidity-pool-card.tsx",
    description: "High performance Apple-styled Liquidity Pool Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/liquidity-pool-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { LiquidityPoolCard } from "@/components/ui/liquidity-pool-card.tsx"`,
    href: "/components/liquiditypoolcard"
  },

  {
    id: "81",
    slug: "marquee",
    title: "Marquee",
    group: "Navigation, Layout & Overlays",
    name: "Marquee",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/marquee.tsx",
    description: "High performance Apple-styled Marquee component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/marquee.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { Marquee } from "@/components/ui/marquee.tsx"`,
    href: "/components/marquee"
  },
  {
    id: "82",
    slug: "multistatebadge",
    title: "Multi State Badge",
    group: "Feedback, Status & Notifications",
    name: "Multi State Badge",
    category: "Feedback, Status & Notifications",
    registry: "Feedback, Status & Notifications",
    file: "components/ui/multi-state-badge.tsx",
    description: "High performance Apple-styled Multi State Badge component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/multi-state-badge.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { MultiStateBadge } from "@/components/ui/multi-state-badge.tsx"`,
    href: "/components/multistatebadge"
  },
  {
    id: "83",
    slug: "multiwalletswitcher",
    title: "Multi Wallet Switcher",
    group: "Wallet & Identity",
    name: "Multi Wallet Switcher",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/multi-wallet-switcher.tsx",
    description: "High performance Apple-styled Multi Wallet Switcher component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/multi-wallet-switcher.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { MultiWalletSwitcher } from "@/components/ui/multi-wallet-switcher.tsx"`,
    href: "/components/multiwalletswitcher"
  },
  {
    id: "91",
    slug: "notificationsstack",
    title: "Notifications Stack",
    group: "Feedback, Status & Notifications",
    name: "Notifications Stack",
    category: "Feedback, Status & Notifications",
    registry: "Feedback, Status & Notifications",
    file: "components/ui/notifications-stack.tsx",
    description: "High performance Apple-styled Notifications Stack component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/notifications-stack.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { NotificationsStack } from "@/components/ui/notifications-stack.tsx"`,
    href: "/components/notificationsstack"
  },
  {
    id: "92",
    slug: "orderbook",
    title: "Order Book",
    group: "Swap, Trade & Orders",
    name: "Order Book",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/order-book.tsx",
    description: "High performance Apple-styled Order Book component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/order-book.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { OrderBook } from "@/components/ui/order-book.tsx"`,
    href: "/components/orderbook"
  },
  {
    id: "93",
    slug: "orderform",
    title: "Order Form",
    group: "Swap, Trade & Orders",
    name: "Order Form",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/order-form.tsx",
    description: "High performance Apple-styled Order Form component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/order-form.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { OrderForm } from "@/components/ui/order-form.tsx"`,
    href: "/components/orderform"
  },
  {
    id: "94",
    slug: "otpinput",
    title: "Otp Input",
    group: "Inputs, Forms & Selectors",
    name: "Otp Input",
    category: "Inputs, Forms & Selectors",
    registry: "Inputs, Forms & Selectors",
    file: "components/ui/otp-input.tsx",
    description: "High performance Apple-styled Otp Input component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/otp-input.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { OtpInput } from "@/components/ui/otp-input.tsx"`,
    href: "/components/otpinput"
  },
  {
    id: "95",
    slug: "passwordinput",
    title: "Password Input",
    group: "Inputs, Forms & Selectors",
    name: "Password Input",
    category: "Inputs, Forms & Selectors",
    registry: "Inputs, Forms & Selectors",
    file: "components/ui/password-input.tsx",
    description: "High performance Apple-styled Password Input component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/password-input.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PasswordInput } from "@/components/ui/password-input.tsx"`,
    href: "/components/passwordinput"
  },
  {
    id: "96",
    slug: "poolcard",
    title: "Pool Card",
    group: "DeFi Positions & Yield",
    name: "Pool Card",
    category: "DeFi Positions & Yield",
    registry: "DeFi Positions & Yield",
    file: "components/ui/pool-card.tsx",
    description: "High performance Apple-styled Pool Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/pool-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PoolCard } from "@/components/ui/pool-card.tsx"`,
    href: "/components/poolcard"
  },
  {
    id: "97",
    slug: "pooltable",
    title: "Pool Table",
    group: "DeFi Positions & Yield",
    name: "Pool Table",
    category: "DeFi Positions & Yield",
    registry: "DeFi Positions & Yield",
    file: "components/ui/pool-table.tsx",
    description: "High performance Apple-styled Pool Table component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/pool-table.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PoolTable } from "@/components/ui/pool-table.tsx"`,
    href: "/components/pooltable"
  },

  {
    id: "99",
    slug: "positioncard",
    title: "Position Card",
    group: "DeFi Positions & Yield",
    name: "Position Card",
    category: "DeFi Positions & Yield",
    registry: "DeFi Positions & Yield",
    file: "components/ui/position-card.tsx",
    description: "High performance Apple-styled Position Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/position-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PositionCard } from "@/components/ui/position-card.tsx"`,
    href: "/components/positioncard"
  },
  {
    id: "100",
    slug: "positiontable",
    title: "Position Table",
    group: "DeFi Positions & Yield",
    name: "Position Table",
    category: "DeFi Positions & Yield",
    registry: "DeFi Positions & Yield",
    file: "components/ui/position-table.tsx",
    description: "High performance Apple-styled Position Table component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/position-table.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PositionTable } from "@/components/ui/position-table.tsx"`,
    href: "/components/positiontable"
  },
  {
    id: "101",
    slug: "pricechart",
    title: "Price Chart",
    group: "Charts & Metrics",
    name: "Price Chart",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/price-chart.tsx",
    description: "High performance Apple-styled Price Chart component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/price-chart.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PriceChart } from "@/components/ui/price-chart.tsx"`,
    href: "/components/pricechart"
  },
  {
    id: "102",
    slug: "priceticker",
    title: "Price Ticker",
    group: "Charts & Metrics",
    name: "Price Ticker",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/price-ticker.tsx",
    description: "High performance Apple-styled Price Ticker component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/price-ticker.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PriceTicker } from "@/components/ui/price-ticker.tsx"`,
    href: "/components/priceticker"
  },
  {
    id: "103",
    slug: "priorityfeeselector",
    title: "Priority Fee Selector",
    group: "Swap, Trade & Orders",
    name: "Priority Fee Selector",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/priority-fee-selector.tsx",
    description: "High performance Apple-styled Priority Fee Selector component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/priority-fee-selector.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { PriorityFeeSelector } from "@/components/ui/priority-fee-selector.tsx"`,
    href: "/components/priorityfeeselector"
  },
  {
    id: "105",
    slug: "qrcode",
    title: "Qr Code",
    group: "Network, Security & Infra",
    name: "Qr Code",
    category: "Network, Security & Infra",
    registry: "Network, Security & Infra",
    file: "components/ui/qr-code.tsx",
    description: "High performance Apple-styled Qr Code component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/qr-code.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { QrCode } from "@/components/ui/qr-code.tsx"`,
    href: "/components/qrcode"
  },

  {
    id: "107",
    slug: "routesummary",
    title: "Route Summary",
    group: "Swap, Trade & Orders",
    name: "Route Summary",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/route-summary.tsx",
    description: "High performance Apple-styled Route Summary component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/route-summary.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { RouteSummary } from "@/components/ui/route-summary.tsx"`,
    href: "/components/routesummary"
  },

  {
    id: "109",
    slug: "runstatsstacks",
    title: "Run Stats Stacks",
    group: "Engagement & Gamification",
    name: "Run Stats Stacks",
    category: "Engagement & Gamification",
    registry: "Engagement & Gamification",
    file: "components/ui/run-stats-stacks.tsx",
    description: "High performance Apple-styled Run Stats Stacks component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/run-stats-stacks.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { RunStatsStacks } from "@/components/ui/run-stats-stacks.tsx"`,
    href: "/components/runstatsstacks"
  },
  {
    id: "110",
    slug: "secretkeywarningbox",
    title: "Secret Key Warning Box",
    group: "Network, Security & Infra",
    name: "Secret Key Warning Box",
    category: "Network, Security & Infra",
    registry: "Network, Security & Infra",
    file: "components/ui/secret-key-warning-box.tsx",
    description: "High performance Apple-styled Secret Key Warning Box component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/secret-key-warning-box.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SecretKeyWarningBox } from "@/components/ui/secret-key-warning-box.tsx"`,
    href: "/components/secretkeywarningbox"
  },

  {
    id: "112",
    slug: "segmentedprogresscard",
    title: "Segmented Progress Card",
    group: "Charts & Metrics",
    name: "Segmented Progress Card",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/segmented-progress-card.tsx",
    description: "High performance Apple-styled Segmented Progress Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/segmented-progress-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SegmentedProgressCard } from "@/components/ui/segmented-progress-card.tsx"`,
    href: "/components/segmentedprogresscard"
  },
  {
    id: "113",
    slug: "signaturestatusbadge",
    title: "Signature Status Badge",
    group: "Transactions & Activity",
    name: "Signature Status Badge",
    category: "Transactions & Activity",
    registry: "Transactions & Activity",
    file: "components/ui/signature-status-badge.tsx",
    description: "High performance Apple-styled Signature Status Badge component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/signature-status-badge.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SignatureStatusBadge } from "@/components/ui/signature-status-badge.tsx"`,
    href: "/components/signaturestatusbadge"
  },
  {
    id: "116",
    slug: "slippageselector",
    title: "Slippage Selector",
    group: "Swap, Trade & Orders",
    name: "Slippage Selector",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/slippage-selector.tsx",
    description: "High performance Apple-styled Slippage Selector component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/slippage-selector.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SlippageSelector } from "@/components/ui/slippage-selector.tsx"`,
    href: "/components/slippageselector"
  },
  {
    id: "117",
    slug: "smoothtabs",
    title: "Smooth Tabs",
    group: "Navigation, Layout & Overlays",
    name: "Smooth Tabs",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/smooth-tabs.tsx",
    description: "High performance Apple-styled Smooth Tabs component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/smooth-tabs.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SmoothTabs } from "@/components/ui/smooth-tabs.tsx"`,
    href: "/components/smoothtabs"
  },
  {
    id: "119",
    slug: "solanaidentitycard",
    title: "Solana Identity Card",
    group: "Wallet & Identity",
    name: "Solana Identity Card",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/solana-identity-card.tsx",
    description: "High performance Apple-styled Solana Identity Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/solana-identity-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SolanaIdentityCard } from "@/components/ui/solana-identity-card.tsx"`,
    href: "/components/solanaidentitycard"
  },

  {
    id: "121",
    slug: "solananftcard",
    title: "Solana Nft Card",
    group: "NFTs",
    name: "Solana Nft Card",
    category: "NFTs",
    registry: "NFTs",
    file: "components/ui/solana-nft-card.tsx",
    description: "High performance Apple-styled Solana Nft Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/solana-nft-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SolanaNftCard } from "@/components/ui/solana-nft-card.tsx"`,
    href: "/components/solananftcard"
  },
  {
    id: "122",
    slug: "solanapaybutton",
    title: "Solana Pay Button",
    group: "Buttons, Actions & Menus",
    name: "Solana Pay Button",
    category: "Buttons, Actions & Menus",
    registry: "Buttons, Actions & Menus",
    file: "components/ui/solana-pay-button.tsx",
    description: "High performance Apple-styled Solana Pay Button component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/solana-pay-button.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SolanaPayButton } from "@/components/ui/solana-pay-button.tsx"`,
    href: "/components/solanapaybutton"
  },

  {
    id: "124",
    slug: "solanatokencard",
    title: "Solana Token Card",
    group: "Tokens & Assets",
    name: "Solana Token Card",
    category: "Tokens & Assets",
    registry: "Tokens & Assets",
    file: "components/ui/solana-token-card.tsx",
    description: "High performance Apple-styled Solana Token Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/solana-token-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SolanaTokenCard } from "@/components/ui/solana-token-card.tsx"`,
    href: "/components/solanatokencard"
  },
  {
    id: "125",
    slug: "solanatransactionstatus",
    title: "Solana Transaction Status",
    group: "Transactions & Activity",
    name: "Solana Transaction Status",
    category: "Transactions & Activity",
    registry: "Transactions & Activity",
    file: "components/ui/solana-transaction-status.tsx",
    description: "High performance Apple-styled Solana Transaction Status component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/solana-transaction-status.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SolanaTransactionStatus } from "@/components/ui/solana-transaction-status.tsx"`,
    href: "/components/solanatransactionstatus"
  },
  {
    id: "126",
    slug: "solanawalletcard",
    title: "Solana Wallet Card",
    group: "Wallet & Identity",
    name: "Solana Wallet Card",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/solana-wallet-card.tsx",
    description: "High performance Apple-styled Solana Wallet Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/solana-wallet-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SolanaWalletCard } from "@/components/ui/solana-wallet-card.tsx"`,
    href: "/components/solanawalletcard"
  },

  {
    id: "129",
    slug: "spinningcounter",
    title: "Spinning Counter",
    group: "Engagement & Gamification",
    name: "Spinning Counter",
    category: "Engagement & Gamification",
    registry: "Engagement & Gamification",
    file: "components/ui/spinning-counter.tsx",
    description: "High performance Apple-styled Spinning Counter component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/spinning-counter.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SpinningCounter } from "@/components/ui/spinning-counter.tsx"`,
    href: "/components/spinningcounter"
  },
  {
    id: "130",
    slug: "stakingcard",
    title: "Staking Card",
    group: "DeFi Positions & Yield",
    name: "Staking Card",
    category: "DeFi Positions & Yield",
    registry: "DeFi Positions & Yield",
    file: "components/ui/staking-card.tsx",
    description: "High performance Apple-styled Staking Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/staking-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { StakingCard } from "@/components/ui/staking-card.tsx"`,
    href: "/components/stakingcard"
  },
  {
    id: "131",
    slug: "statcard",
    title: "Stat Card",
    group: "Charts & Metrics",
    name: "Stat Card",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/stat-card.tsx",
    description: "High performance Apple-styled Stat Card component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/stat-card.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { StatCard } from "@/components/ui/stat-card.tsx"`,
    href: "/components/statcard"
  },
  {
    id: "132",
    slug: "steptrackerwidget",
    title: "Step Tracker Widget",
    group: "Engagement & Gamification",
    name: "Step Tracker Widget",
    category: "Engagement & Gamification",
    registry: "Engagement & Gamification",
    file: "components/ui/step-tracker-widget.tsx",
    description: "High performance Apple-styled Step Tracker Widget component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/step-tracker-widget.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { StepTrackerWidget } from "@/components/ui/step-tracker-widget.tsx"`,
    href: "/components/steptrackerwidget"
  },
  {
    id: "134",
    slug: "successcheck",
    title: "Success Check",
    group: "Feedback, Status & Notifications",
    name: "Success Check",
    category: "Feedback, Status & Notifications",
    registry: "Feedback, Status & Notifications",
    file: "components/ui/success-check.tsx",
    description: "High performance Apple-styled Success Check component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/success-check.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { SuccessCheck } from "@/components/ui/success-check.tsx"`,
    href: "/components/successcheck"
  },

  {
    id: "136",
    slug: "timeline",
    title: "Timeline",
    group: "Engagement & Gamification",
    name: "Timeline",
    category: "Engagement & Gamification",
    registry: "Engagement & Gamification",
    file: "components/ui/timeline.tsx",
    description: "High performance Apple-styled Timeline component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/timeline.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { Timeline } from "@/components/ui/timeline.tsx"`,
    href: "/components/timeline"
  },
  {
    id: "137",
    slug: "togglegroup",
    title: "Toggle Group",
    group: "Inputs, Forms & Selectors",
    name: "Toggle Group",
    category: "Inputs, Forms & Selectors",
    registry: "Inputs, Forms & Selectors",
    file: "components/ui/toggle-group.tsx",
    description: "High performance Apple-styled Toggle Group component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/toggle-group.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { ToggleGroup } from "@/components/ui/toggle-group.tsx"`,
    href: "/components/togglegroup"
  },
  {
    id: "138",
    slug: "togglepill",
    title: "Toggle Pill",
    group: "Inputs, Forms & Selectors",
    name: "Toggle Pill",
    category: "Inputs, Forms & Selectors",
    registry: "Inputs, Forms & Selectors",
    file: "components/ui/toggle-pill.tsx",
    description: "High performance Apple-styled Toggle Pill component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/toggle-pill.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TogglePill } from "@/components/ui/toggle-pill.tsx"`,
    href: "/components/togglepill"
  },
  {
    id: "140",
    slug: "tokencommand",
    title: "Token Command",
    group: "Tokens & Assets",
    name: "Token Command",
    category: "Tokens & Assets",
    registry: "Tokens & Assets",
    file: "components/ui/token-command.tsx",
    description: "High performance Apple-styled Token Command component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/token-command.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TokenCommand } from "@/components/ui/token-command.tsx"`,
    href: "/components/tokencommand"
  },
  {
    id: "141",
    slug: "tokenicongroup",
    title: "Token Icon Group",
    group: "Tokens & Assets",
    name: "Token Icon Group",
    category: "Tokens & Assets",
    registry: "Tokens & Assets",
    file: "components/ui/token-icon-group.tsx",
    description: "High performance Apple-styled Token Icon Group component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/token-icon-group.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TokenIconGroup } from "@/components/ui/token-icon-group.tsx"`,
    href: "/components/tokenicongroup"
  },

  {
    id: "143",
    slug: "tokeninput",
    title: "Token Input",
    group: "Tokens & Assets",
    name: "Token Input",
    category: "Tokens & Assets",
    registry: "Tokens & Assets",
    file: "components/ui/token-input.tsx",
    description: "High performance Apple-styled Token Input component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/token-input.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TokenInput } from "@/components/ui/token-input.tsx"`,
    href: "/components/tokeninput"
  },
  {
    id: "144",
    slug: "tokenlistitem",
    title: "Token List Item",
    group: "Tokens & Assets",
    name: "Token List Item",
    category: "Tokens & Assets",
    registry: "Tokens & Assets",
    file: "components/ui/token-list-item.tsx",
    description: "High performance Apple-styled Token List Item component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/token-list-item.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TokenListItem } from "@/components/ui/token-list-item.tsx"`,
    href: "/components/tokenlistitem"
  },

  {
    id: "146",
    slug: "tokenpair",
    title: "Token Pair",
    group: "Tokens & Assets",
    name: "Token Pair",
    category: "Tokens & Assets",
    registry: "Tokens & Assets",
    file: "components/ui/token-pair.tsx",
    description: "High performance Apple-styled Token Pair component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/token-pair.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TokenPair } from "@/components/ui/token-pair.tsx"`,
    href: "/components/tokenpair"
  },

  {
    id: "148",
    slug: "tradebox",
    title: "Trade Box",
    group: "Swap, Trade & Orders",
    name: "Trade Box",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/trade-box.tsx",
    description: "High performance Apple-styled Trade Box component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/trade-box.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TradeBox } from "@/components/ui/trade-box.tsx"`,
    href: "/components/tradebox"
  },
  {
    id: "149",
    slug: "tradebuttons",
    title: "Trade Buttons",
    group: "Swap, Trade & Orders",
    name: "Trade Buttons",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/trade-buttons.tsx",
    description: "High performance Apple-styled Trade Buttons component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/trade-buttons.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TradeButtons } from "@/components/ui/trade-buttons.tsx"`,
    href: "/components/tradebuttons"
  },
  {
    id: "150",
    slug: "transactionmodal",
    title: "Transaction Modal",
    group: "Transactions & Activity",
    name: "Transaction Modal",
    category: "Transactions & Activity",
    registry: "Transactions & Activity",
    file: "components/ui/transaction-modal.tsx",
    description: "High performance Apple-styled Transaction Modal component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/transaction-modal.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TransactionModal } from "@/components/ui/transaction-modal.tsx"`,
    href: "/components/transactionmodal"
  },
  {
    id: "151",
    slug: "transactionreceipt",
    title: "Transaction Receipt",
    group: "Transactions & Activity",
    name: "Transaction Receipt",
    category: "Transactions & Activity",
    registry: "Transactions & Activity",
    file: "components/ui/transaction-receipt.tsx",
    description: "High performance Apple-styled Transaction Receipt component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/transaction-receipt.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TransactionReceipt } from "@/components/ui/transaction-receipt.tsx"`,
    href: "/components/transactionreceipt"
  },

  {
    id: "153",
    slug: "trendbadge",
    title: "Trend Badge",
    group: "Feedback, Status & Notifications",
    name: "Trend Badge",
    category: "Feedback, Status & Notifications",
    registry: "Feedback, Status & Notifications",
    file: "components/ui/trend-badge.tsx",
    description: "High performance Apple-styled Trend Badge component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/trend-badge.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TrendBadge } from "@/components/ui/trend-badge.tsx"`,
    href: "/components/trendbadge"
  },
  {
    id: "154",
    slug: "txntable",
    title: "Txn Table",
    group: "Transactions & Activity",
    name: "Txn Table",
    category: "Transactions & Activity",
    registry: "Transactions & Activity",
    file: "components/ui/txn-table.tsx",
    description: "High performance Apple-styled Txn Table component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/txn-table.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TxnTable } from "@/components/ui/txn-table.tsx"`,
    href: "/components/txntable"
  },
  {
    id: "155",
    slug: "txntoast",
    title: "Txn Toast",
    group: "Transactions & Activity",
    name: "Txn Toast",
    category: "Transactions & Activity",
    registry: "Transactions & Activity",
    file: "components/ui/txn-toast.tsx",
    description: "High performance Apple-styled Txn Toast component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/txn-toast.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { TxnToast } from "@/components/ui/txn-toast.tsx"`,
    href: "/components/txntoast"
  },
  {
    id: "156",
    slug: "underlayactionsheet",
    title: "Underlay Action Sheet",
    group: "Navigation, Layout & Overlays",
    name: "Underlay Action Sheet",
    category: "Navigation, Layout & Overlays",
    registry: "Navigation, Layout & Overlays",
    file: "components/ui/underlay-action-sheet.tsx",
    description: "High performance Apple-styled Underlay Action Sheet component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/underlay-action-sheet.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { UnderlayActionSheet } from "@/components/ui/underlay-action-sheet.tsx"`,
    href: "/components/underlayactionsheet"
  },

  {
    id: "159",
    slug: "walletsheet",
    title: "Wallet Sheet",
    group: "Wallet & Identity",
    name: "Wallet Sheet",
    category: "Wallet & Identity",
    registry: "Wallet & Identity",
    file: "components/ui/wallet-sheet.tsx",
    description: "High performance Apple-styled Wallet Sheet component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/wallet-sheet.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { WalletSheet } from "@/components/ui/wallet-sheet.tsx"`,
    href: "/components/walletsheet"
  },
  {
    id: "164",
    slug: "progressring",
    title: "Progress Ring",
    group: "Charts & Metrics",
    name: "Progress Ring",
    category: "Charts & Metrics",
    registry: "Charts & Metrics",
    file: "components/ui/progress-ring.tsx",
    description: "High performance Apple-styled Progress Ring component for Solana & Web3 applications.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/progress-ring.tsx`,
    interaction: "Interactive component preview.",
    usage: `import { ProgressRing } from "@/components/ui/progress-ring.tsx"`,
    href: "/components/progressring"
  },

  {
    id: "168",
    slug: "tradetogglepill",
    title: "Trade Toggle Pill",
    group: "Swap, Trade & Orders",
    name: "Trade Toggle Pill",
    category: "Swap, Trade & Orders",
    registry: "Swap, Trade & Orders",
    file: "components/ui/trade-toggle-pill.tsx",
    description: "A segmented pill toggle for switching between buy and sell actions in crypto trading interfaces.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/trade-toggle-pill.tsx`,
    interaction: "Click either side to switch between Buy and Sell. The active side highlights with a contrasting fill.",
    usage: `import { TradeTogglePill } from "@/components/ui/trade-toggle-pill"`,
    href: "/components/tradetogglepill"
  },

  {
    id: "170",
    slug: "statusbadgepill",
    title: "Status Badge Pill",
    group: "Feedback, Status & Notifications",
    name: "Status Badge Pill",
    category: "Feedback, Status & Notifications",
    registry: "Feedback, Status & Notifications",
    file: "components/ui/status-badge-pill.tsx",
    description: "An animated status pill badge with pastel variants covering add, waiting, success, pending, failed, and more states.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/status-badge-pill.tsx`,
    interaction: "Click the badge to cycle through states. Use the pill switcher below to jump to any state directly.",
    usage: `import { StatusBadgePill } from "@/components/ui/status-badge-pill"`,
    href: "/components/statusbadgepill"
  },

  {
    id: "172",
    slug: "uxbutton",
    title: "Button",
    group: "Buttons, Actions & Menus",
    name: "Button",
    category: "Buttons, Actions & Menus",
    registry: "Buttons, Actions & Menus",
    file: "components/uxdotsol/components/button.tsx",
    description: "Reusable button component with variants, sizes, and accessible interaction states.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/uxdotsol/components/button.tsx`,
    interaction: "Click buttons to trigger actions. Includes primary, secondary, outline, ghost, destructive, and success variants.",
    usage: `import { UxSolButton } from "@/components/uxdotsol/components/button"`,
    href: "/components/uxbutton"
  },

  {
    id: "176",
    slug: "drawcheckbox",
    title: "Draw Checkbox",
    group: "Forms & Inputs",
    name: "Draw Checkbox",
    category: "Forms & Inputs",
    registry: "Forms & Inputs",
    file: "components/ui/draw-checkbox.tsx",
    description: "Animated SVG pathLength line-drawing checkboxes with tactile spring animations for security checklists and transaction approvals.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/draw-checkbox.tsx`,
    interaction: "Click checklist rows to trigger the smooth SVG stroke drawing animation.",
    usage: `import { DrawCheckbox } from "@/components/ui/draw-checkbox"`,
    href: "/components/drawcheckbox"
  },
  {
    id: "177",
    slug: "multiplestatebutton",
    title: "Multi-State Action Button",
    group: "Buttons, Actions & Menus",
    name: "Multi-State Action Button",
    category: "Buttons, Actions & Menus",
    registry: "Buttons, Actions & Menus",
    file: "components/ui/multiple-state-button.tsx",
    description: "A security action button with fluid state machine transitions between idle, loading signatures, and success verification states.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/multiple-state-button.tsx`,
    interaction: "Click the button to trigger the signature broadcast and vault verification cycle.",
    usage: `import { MultipleStateButton } from "@/components/ui/multiple-state-button"`,
    href: "/components/multiplestatebutton"
  },
  {
    id: "182",
    slug: "metrics01",
    title: "Metrics 01",
    group: "Special",
    name: "Metrics 01",
    category: "Special",
    registry: "Special",
    file: "components/ui/metrics-01.tsx",
    description: "A metrics section with a line chart, summary metrics, and date range header.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/metrics-01.tsx`,
    interaction: "Interactive analytics insights display with line chart visualization.",
    usage: `import { Metrics01 } from "@/components/ui/metrics-01"`,
    href: "/components/metrics01"
  },
  {
    id: "185",
    slug: "bankbalancecard",
    title: "Bank Balance Card",
    group: "Special",
    name: "Bank Balance Card",
    category: "Special",
    registry: "Special",
    file: "components/ui/bank-balance-card.tsx",
    description: "Sleek bank balance widget displaying active accounts and stacked VISA cards with custom color gradients.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/bank-balance-card.tsx`,
    interaction: "Interactive stacked VISA cards with selection state.",
    usage: `import { BankBalanceCard } from "@/components/ui/bank-balance-card"`,
    href: "/components/bankbalancecard"
  },
  {
    id: "187",
    slug: "withdrawalcard",
    title: "Request Withdrawal Card",
    group: "Special",
    name: "Request Withdrawal Card",
    category: "Special",
    registry: "Special",
    file: "components/ui/withdrawal-card.tsx",
    description: "Request withdrawal card with percentage preset chips, instant withdrawal toggle, fee estimation, and receive breakdown.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/withdrawal-card.tsx`,
    interaction: "Interactive form input, percentage selectors, and instant fee toggle.",
    usage: `import { WithdrawalCard } from "@/components/ui/withdrawal-card"`,
    href: "/components/withdrawalcard"
  },


  {
    id: "190",
    slug: "animatednumberflow",
    title: "Animated Number Flow",
    group: "Special",
    name: "Animated Number Flow",
    category: "Special",
    registry: "Special",
    file: "components/ui/animated-number-flow.tsx",
    description: "Skiper37 Animated Number Flow component combining NumberFlow with Framer Motion for countdown, spring counter, random ticker, and motion value transitions.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/animated-number-flow.tsx`,
    interaction: "Interactive countdown controls, scroll viewport triggers, and animated number transitions.",
    usage: `import { Skiper37 } from "@/components/ui/animated-number-flow"`,
    href: "/components/animatednumberflow"
  },
  {
    id: "191",
    slug: "verificationbadges",
    title: "Verification Badges",
    group: "Feedback, Status & Notifications",
    name: "Verification Badges",
    category: "Feedback, Status & Notifications",
    registry: "Feedback, Status & Notifications",
    file: "components/ui/verification-badge.tsx",
    description: "Official verification badges in Scalloped Seal and Circle shapes with Blue, Black, Gold, Purple, Emerald, and Silver styles.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/verification-badge.tsx`,
    interaction: "Interactive SVG badges with size and color variants.",
    usage: `import { VerificationBadge, VerificationBadges } from "@/components/ui/verification-badge"`,
    href: "/components/verificationbadges"
  },
  {
    id: "192",
    slug: "floatinglabel",
    title: "Floating Label Input",
    group: "Special",
    name: "Floating Label Input",
    category: "Special",
    registry: "Special",
    file: "components/ui/floating-label.tsx",
    description: "Input where label makes room smoothly above the field instead of disappearing, featuring spring lift physics, max length counter, and invalid state styling.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/floating-label.tsx`,
    interaction: "Interactive spring floating label on focus and text entry.",
    usage: `import { FloatingLabelInput } from "@/components/ui/floating-label"`,
    href: "/components/floatinglabel"
  },
  {
    id: "193",
    slug: "passwordstrength",
    title: "Password Strength",
    group: "Special",
    name: "Password Strength",
    category: "Special",
    registry: "Special",
    file: "components/ui/password-strength.tsx",
    description: "Multi-segment animated password strength meter evaluating length, casing, numbers, symbols, and common pattern detection with ARIA live region support.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/password-strength.tsx`,
    interaction: "Live strength meter evaluation and requirement checklist.",
    usage: `import { PasswordStrength, usePasswordStrength } from "@/components/ui/password-strength"`,
    href: "/components/passwordstrength"
  },
  {
    id: "194",
    slug: "tasksteps",
    title: "Task Steps",
    group: "Special",
    name: "Task Steps",
    category: "Special",
    registry: "Special",
    file: "components/ui/task-steps.tsx",
    description: "Narrated step progress indicator for pipeline runs, deploys, and system tasks with status spinner, completion checkmarks, and duration meta tags.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/task-steps.tsx`,
    interaction: "Interactive step state progression and status indicators.",
    usage: `import { TaskSteps } from "@/components/ui/task-steps"`,
    href: "/components/tasksteps"
  },
  {
    id: "195",
    slug: "wizardsteps",
    title: "Wizard Steps",
    group: "Special",
    name: "Wizard Steps",
    category: "Special",
    registry: "Special",
    file: "components/ui/wizard-steps.tsx",
    description: "Direction-aware multi-step onboarding wizard with progress track tiles, panel transition springs, keyboard navigation, and customizable action controls.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/wizard-steps.tsx`,
    interaction: "Interactive step navigation and panel animations.",
    usage: `import { WizardSteps, useWizard } from "@/components/ui/wizard-steps"`,
    href: "/components/wizardsteps"
  },
  {
    id: "196",
    slug: "valueflash",
    title: "Value Flash",
    group: "Special",
    name: "Value Flash",
    category: "Special",
    registry: "Special",
    file: "components/ui/value-flash.tsx",
    description: "Real-time numerical change indicator that flashes green on increase and red on decrease with rolling spring motion and direction glyphs.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/value-flash.tsx`,
    interaction: "Dynamic value mutation flash animations.",
    usage: `import { ValueFlash, useValueFlash } from "@/components/ui/value-flash"`,
    href: "/components/valueflash"
  },
  {
    id: "197",
    slug: "logomarquee",
    title: "Logo Marquee",
    group: "Special",
    name: "Logo Marquee",
    category: "Special",
    registry: "Special",
    file: "components/ui/logo-marquee.tsx",
    description: "Continuous infinite looping logo marquee banner with pause-on-hover/focus interaction, resize observer auto-wrap, and left/right drift directions.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/logo-marquee.tsx`,
    interaction: "Continuous marquee drift with pointer and focus pause controls.",
    usage: `import { LogoMarquee, useLogoMarquee } from "@/components/ui/logo-marquee"`,
    href: "/components/logomarquee"
  },
  {
    id: "198",
    slug: "presenceavatars",
    title: "Presence Avatars",
    group: "Special",
    name: "Presence Avatars",
    category: "Special",
    registry: "Special",
    file: "components/ui/presence-avatars.tsx",
    description: "Dynamic presence avatar stack where joining and leaving users trigger real-time spring layout transitions, automatic initials fallback, and overflow counters.",
    source: `${REGISTRY_HOMEPAGE}/blob/main/components/ui/presence-avatars.tsx`,
    interaction: "Interactive presence join/leave spring animations and overflow selection.",
    usage: `import { PresenceAvatars, usePresence } from "@/components/ui/presence-avatars"`,
    href: "/components/presenceavatars"
  }
];










